name: SonarQube Scan

on: [push]

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: sqp_97087f737c9ad77b64cb800d770a62faf26b63d8
          SONAR_HOST_URL: https://user311046463-wy6bad35.tunnel.vk-apps.com/  # Для прода: заменить на ваш сервер
