name: DevSecOps CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    # SAST: Bandit
    - name: SAST Scan (Bandit)
      run: |
        pip install bandit
        bandit -r . --severity-level high --confidence-level high
        
    # Security Scan (Trivy) - из Модуля 1
    - name: Container Scan (Trivy)
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
    # Secrets Detection
    - name: Secrets Scan (TruffleHog)
      uses: trufflesecurity/trufflehog@main
      with:
        args: '--regex --entropy=False --max_depth=1 .'
