name: CI Pipeline
on: [push]
jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ SONAR_TOKEN }}
          SONAR_HOST_URL: https://user311046463-wy6bad35.tunnel.vk-apps.com/  # Для прода: заменить на ваш сервер
