name: DevSecOps CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    # Сборка образа
    - name: Build Docker image
      run: docker build -t devsecops-app .
      
    # Запуск контейнера с пробросом портов
    - name: Run app container
      run: |
        docker run -d --name devsecops-app-container -p 5000:5000 devsecops-app
        
    # Ожидание запуска приложения
    - name: Wait for application to start
      continue-on-error: true  
      run: |
        # Ждем пока приложение станет доступно
        echo "Waiting for app to start..."
        docker logs devsecops-app-container  # Для отладки
        timeout 30 bash -c 'while ! curl -s http://localhost:5000 >/dev/null; do sleep 2; done'
        echo "Application is ready!"
    # DAST: OWASP ZAP
    - name: DAST Scan (ZAP)
      uses: zaproxy/action-full-scan@v0.7.0
      with:
        target: 'http://localhost:5000'
        cmd_options: '--network host'  # Ключевое исправление!
        rules: 'rules/risk-3'

    # IaC Security: Checkov
    - name: IaC Scan (Checkov)
      uses: bridgecrewio/checkov-action@v12
      with:
        directory: .
        skip_check: CKV_DOCKER_2

    # Останавливаем контейнер
    - name: Stop container
      run: |
        docker stop devsecops-app-container || true
        docker rm devsecops-app-container || true
