name: DevSecOps CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      app:  # Добавляем сервис для правильной работы сети
        image: devsecops-app
        ports:
          - 5000:5000

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    # Сборка образа
    - name: Build Docker image
      run: docker build -t devsecops-app .

    # Запуск контейнера в фоне с явным именем
    - name: Run app container
      run: |
        docker run -d --name running-app -p 5000:5000 devsecops-app

    # Ожидание запуска приложения
    - name: Wait for application to start
      run: |
        echo "Waiting for app to start..."
        docker logs running-app  # Покажем логи для отладки
        timeout 60 bash -c 'while ! docker exec running-app curl -s http://localhost:5000; do sleep 2; done'
        echo "Application is ready!"

    # DAST: OWASP ZAP
    - name: DAST Scan (ZAP)
      uses: zaproxy/action-full-scan@v0.7.0
      with:
        target: 'http://localhost:5000'  # Для GitHub Actions services
        cmd_options: '--network host'    # Критически важно!
        rules: 'rules/risk-3'

    # IaC Security: Checkov
    - name: IaC Scan (Checkov)
      uses: bridgecrewio/checkov-action@v12
      with:
        directory: .
        skip_check: CKV_DOCKER_2

    # Останавливаем контейнер
    - name: Stop container
      run: docker stop running-app || true
